// Type declarations for kavach packages, virtual modules, and third-party libs
// that ship without declaration files.

// @rokkit/states ships JS source only — no .d.ts. Declare as module to silence
// implicit-any cascade across @rokkit/ui and @rokkit/app source files.
declare module '@rokkit/states' {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const vibe: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const messages: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  type ProxyItem = any;
  export { vibe, messages };
  export type { ProxyItem };
  export default vibe;
}

// $kavach/providers is a virtual module generated by @kavach/vite.
declare module '$kavach/providers' {
  export interface AuthProviderConfig {
    name: string;
    label?: string;
    mode?: string;
  }
  export const providers: AuthProviderConfig[];
}

// @kavach/ui ships with an empty dist/index.d.ts (build artifact issue).
// Declare the components that the app actually uses.
declare module '@kavach/ui' {
  import type { SvelteComponent } from 'svelte';
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const AuthProvider: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const AuthPage: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const LoginCard: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const AuthButton: any;
}

declare module '$kavach/auth' {
  import type { Handle } from '@sveltejs/kit';
  export const kavach: {
    handle: Handle;
  };
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const adapter: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const logger: any;
}

declare module '@kavach/adapter-supabase' {
  export interface ActionResponse {
    data: unknown | null;
    error: unknown | null;
    status: number;
    count?: number;
  }

  export function getActions(
    client: unknown,
    schema?: string
  ): {
    get(entity: string, params?: Record<string, unknown>): Promise<ActionResponse>;
    put(entity: string, data: Record<string, unknown>): Promise<ActionResponse>;
    post(entity: string, data: Record<string, unknown>): Promise<ActionResponse>;
    patch(entity: string, input?: { data?: Record<string, unknown>; filter?: Record<string, string> }): Promise<ActionResponse>;
    delete(entity: string, input?: { filter?: Record<string, string> }): Promise<ActionResponse>;
    call(entity: string, data: Record<string, unknown>): Promise<ActionResponse>;
    connection: unknown;
  };
}

declare module '@kavach/query' {
  export interface FilterDescriptor {
    column: string;
    op: string;
    value: string | string[] | null;
  }

  export interface OrderDescriptor {
    column: string;
    ascending: boolean;
  }

  export interface QueryParams {
    columns: string;
    filters: FilterDescriptor[];
    orders: OrderDescriptor[];
    limit?: number;
    offset?: number;
    count?: string;
  }

  export function parseFilter(filter?: Record<string, string>): FilterDescriptor[];
  export function parseOrder(order?: string): OrderDescriptor[];
  export function parseQueryParams(data?: Record<string, unknown>): QueryParams;
}

declare module 'kavach' {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export function createKavach(adapter: any, options?: any): Record<string, any>;
}
